#ifndef MBEDTLS_USER_CONFIG_H
#define MBEDTLS_USER_CONFIG_H

#if defined(MBEDTLS_SSL_MAX_CONTENT_LEN)
#undef MBEDTLS_SSL_MAX_CONTENT_LEN
#endif
#define MBEDTLS_SSL_MAX_CONTENT_LEN             8192

//#define MBEDTLS_DEBUG_C

#endif /* MBEDTLS_USER_CONFIG_H */
